apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: yashpod-1
  name: yashpod-1
spec:
  containers:
  - image: sikkewal/customer1
    name: yashpod-1
    env:
    - name: myapp
      value: app3
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
