apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: yashservice-1
  name: yashservice-1
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector: #POD finder using label
    run: yashpod-1 #Label of pod
  type: NodePort
status:
  loadBalancer: {}
