apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: yashpod1
  name: yashpod1
spec:
  containers:
  - image: busybox
    command: ['sh', '-c', 'ping fb.com']
    name: yashpod1
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
